- name: "Configuring octopi"
  template: src={{item.filename}} dest="{{octoprint_dir}}/{{item.filename}}" mode="{{item.mode}}" group=pi owner=pi
  with_items:
    - { filename: "config.yaml", mode: "644" }
    - { filename: "users.yaml", mode: "600" }
  tags:
    - octoprint-config
  become: yes