- name: "Installing datasource {{datasource_name}}"
  include_tasks: install_grafana_datasource.yml
  vars:
    datasource_type: "prometheus"
    datasource_url: "http://{{prometheus_host}}:{{prometheus_port}}"
    datasource_tlsCACert: ""