- id: '1672951034106'
  alias: Turn off paper shredder after 10min
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: e6d7bf1bbd2e3a497293743075eda631
    entity_id: switch.paper_shredder
    domain: switch
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: e6d7bf1bbd2e3a497293743075eda631
    entity_id: switch.paper_shredder
    domain: switch
  - service: script.notify_joris
    data:
      message: Paper shredder turned off
      expire: 00:01:00
  mode: single
- id: '1691673603701'
  alias: Turn off Dyson when backdoor is open
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door_contact
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.back_door_contact
      state: 'on'
    then:
    - service: fan.turn_off
      data: {}
      target:
        device_id: 09fe090cedf12eb82a8046fcbc6d24cc
    else:
    - service: fan.turn_on
      data: {}
      target:
        device_id: 09fe090cedf12eb82a8046fcbc6d24cc
    alias: Turn On/Off Dyson
  mode: single
