# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Allow access through reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret local_reverse_proxy

frontend:
  themes: !include_dir_merge_named themes
  # Card Mod Perf improvements, see here: https://github.com/thomasloven/lovelace-card-mod#performance-improvements
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 75
    icon: mdi:home

notify:
  - name: family
    platform: group
    services:
      - service: mobile_app_iphone_13_pro_max
      - service: mobile_app_iphone_van_ilse

group: !include groups.yaml
# By "labeling" the 'automation' key, we can use it multiple times and import from different locations
# This allows us to enable both handwritten and UI-generated automations
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
light: !include lights.yaml
cover: !include covers.yaml
sensor: !include sensors/sensor.yaml
binary_sensor: !include sensors/binary.yaml
template: !include_dir_merge_list templates/

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

homematic:
  interfaces:
    rf:
      host: !secret homematic_host
      resolvenames: json

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscription_id

homekit:
  - filter:
      include_entities:
        - light.nightstand_joris

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
# Non UI Integrations (need to be manually configured in here and required HA restart)

# https://github.com/thomasloven/hass-browser_mod
# Used for auto navigating wall-mounted ipads using HA automations
# browser_mod:

# NOT WORKING
# dyson
# Seems to have been broken for a while: https://github.com/home-assistant/core/issues/46400
# Using https://github.com/shenxn/ha-dyson via HACS instead
# dyson:
#   username: !secret dyson_username
#   password: !secret dyson_password
#   language: !secret dyson_language

# spotcast:
#   sp_key: !secret spotcast_sp_key
#   sp_dc: !secret spotcast_sp_dc
