- name: restart_ssh
  service: name=ssh state=restarted
  become: yes

- name: restart_logind
  service: name=systemd-logind state=restarted
  become: yes

- name: save_iptables
  shell: "netfilter-persistent save"
  become: yes