- platform: workday
  country: NL
  workdays: [mon, tue, wed, thu, fri]

- platform: ping
  host: !secret mbp_joris_host
  name: mbp_joris_active
  scan_interval: 5

- platform: tod
  name: Is Evening 2
  before: sunrise
  after: sunset
  after_offset: "-00:45"

- platform: tod
  name: Is Night
  after: "00:00"
  before: "sunrise"
  before_offset: "-02:01"

- platform: tod
  name: Is Early Morning
  after: sunrise
  after_offset: "-02:00"
  before: "07:00"

- platform: tod
  name: Is Morning
  after: "07:00"
  before: "12:00"

- platform: tod
  name: Is Afternoon
  after: "12:00"
  before: "18:00"
# - platform: trend
#   sensors:
#     cooking_trend:
#       entity_id: sensor.kitchen_hood_temperature
#       sample_duration: 30
#       max_samples: 10
#        min_gradient: 0.05
