- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use

- platform: afvalinfo
  resources:
    - pbd
    - gft
    - papier
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber

- platform: history_stats
  name: Sauna Session Duration
  entity_id: switch.sauna_leg_heater
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 2

- platform: history_stats
  name: Sauna Session Counter
  entity_id: switch.sauna_leg_heater
  state: "on"
  type: count
  # start: "{{ 0 }}"
  end: "{{ now() }}"
  duration:
    days: 30


# Below is the equivalent of the following influxDB query:
# SELECT last("value"), time FROM "homeassistant"."autogen"."mm" WHERE "value" > 0.5 AND "entity_id"='gw2000a_event_rain_rate_piezo'

# Unfortunately, the influxdb sensor doesn't allow for the time to be returned instead of the value
# Someone else asking, no answer: https://community.home-assistant.io/t/influxdb-sensor-get-value-and-time/168152
# So we'll be using a command_line sensor to work around this

# - platform: influxdb
#   api_version: 1
#   host: !secret influxdb_host
#   port: !secret influxdb_port
#   database: !secret influxdb_database
#   username: !secret influxdb_username
#   password: !secret influxdb_password
#   queries:
#     - name: Influx rain mm
#       unit_of_measurement: mm
#       value_template: "{{ value_json }}"
#       group_function: last
#       where: '"entity_id" = ''gw2000a_event_rain_rate_piezo'' AND "value" > 0.5 AND time > now() - 90d'
#       measurement: '"mm"'
#       field: value
#       database: homeassistant

# Power Plug filtering #################################################################################################

- platform: filter
  name: "Quooker Dishwasher Energy Filtered"
  entity_id: sensor.quooker_dishwasher_power_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 10
      radius: 5.0

- platform: filter
  name: "Dryer Energy Filtered"
  entity_id: sensor.dryer_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 10
      radius: 5.0
