- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use

- platform: afvalinfo
  resources:
    - pbd
    - gft
    - papier
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber

- platform: history_stats
  name: Sauna Session Duration
  entity_id: switch.sauna_leg_heater
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 2

- platform: history_stats
  name: Sauna Session Counter
  entity_id: switch.sauna_leg_heater
  state: "on"
  type: count
  # start: "{{ 0 }}"
  end: "{{ now() }}"
  duration:
    days: 30

# Power Plug filtering #################################################################################################

- platform: filter
  name: "Quooker Dishwasher Energy Filtered"
  entity_id: sensor.quooker_dishwasher_power_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 10
      radius: 5.0

- platform: filter
  name: "Dryer Energy Filtered"
  entity_id: sensor.dryer_electric_consumption_kwh
  filters:
    - filter: outlier
      window_size: 10
      radius: 5.0
