################################################################################
# House Scenes                                                                 #
################################################################################
- name: Sleeping
  entities:
    group.lights_outside:
        state: off
    group.lights_downstairs:
        state: off
    group.lights_downstairs_automatic:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_select.camera_preset:
        option: All On
    input_boolean.cooking:
        state: off
    input_select.living_preset:
        option: NoPreset

- name: Day
  entities:
    input_select.camera_preset:
        option: Home

- name: Evening
  entities:
    input_select.camera_preset:
        option: Home
    group.lights_outside:
        state: on
    light.living_ambience_lamp_1:
        state: on
        kelvin: 2200
        brightness_pct: 20
        # Apparently brightness_pct doesn't work on a light group, hence why this is living_ambience_lamp_1
        # and not kantoor_sfeer_verlichting
    light.office_ambience_lamp_1:
        state: on
        kelvin: 2000
        brightness_pct: 75

    # switch.christmas_tree:
    #     state: on
    # switch.christmas_ambience_office:
    #     state: on


# When away, don't turn off lights_downstairs_automatic or group.lights_outside
# These are controlled automatically for security reasons
- name: Away
  entities:
    group.lights_downstairs:
        state: off
    group.lights_upstairs:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_boolean.cooking:
        state: off
    input_select.camera_preset:
        option: All On
    input_select.living_preset:
        option: NoPreset