########################################################################################################################
# Bedrooms Kids                                                                                                        #
########################################################################################################################

################################################################################
# Climate control                                                              #
################################################################################

- alias: Start heating in Kids bedroom when switching on switch
  id: bedroom_kids_start_heating
  trigger:
    - platform: state
      entity_id:
        - input_boolean.heat_bedroom_mats
        - input_boolean.heat_bedroom_hannah
  variables:
    kid: "{{ 'mats' if (trigger.to_state.entity_id == 'input_boolean.heat_bedroom_mats') else 'hannah' }}"
    living_room_temp: "{{ 26 if (trigger.to_state.state == 'on') else states('input_number.living_room_fallback_temperature')}}"
    kid_room_temp: "{{ 23 if (trigger.to_state.state == 'on') else 19 }}"
  action:
    - choose:
        - alias: Store fallback living room temperature before turning up the heat
          conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: input_number.set_value
              target:
                entity_id: input_number.living_room_fallback_temperature
              data:
                value: "{{ state_attr('climate.living_room', 'temperature') }}"
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room
        temperature: "{{living_room_temp}}"
    - service: climate.set_temperature
      data:
        entity_id: "climate.bedroom_{{kid}}"
        temperature: "{{kid_room_temp}}"
    - service: script.notify_joris
      data:
        tag: "heating-kids-bedroom-{{kid}}"
        expire: "02:00:00"
        message: >
          {% if (trigger.to_state.state == 'on') %}
            Started heating bedroom {{kid | capitalize}}
          {% else %}
            Stopped heating bedroom {{kid | capitalize}}
          {% endif %}

# - alias: Notify when too cold in Hannah's room
#   id: bedroom_hannah_temperature_notify
#   trigger:
#     - platform: numeric_state
#       entity_id: climate.bedroom_hannah
#       attribute: current_temperature
#       below: 18
#       for: "00:01:00"
#   action:
#     - service: notify.notify
#       data:
#         message: >
#           It's cold!
#           Bedroom Hannah: {{state_attr("climate.bedroom_hannah", "current_temperature") }}C
#           Bedroom Mats: {{state_attr("climate.bedroom_mats", "current_temperature") }}C
#           Master Bedroom:  {{state_attr("climate.master_bedroom", "current_temperature") }}C
#         data:
#           tag: bedroom-kids-cold

- alias: Notify when kids room have been closed for 48hrs
  id: bedrooms_kids_window_notify
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bedroom_hannah_window_contact
        - binary_sensor.bedroom_mats_window_contact
      to: "off"
      for: "48:00:00"
  action:
    - service: notify.notify
      data:
        message: It's been more than 48hrs since the kids window were last opened. Suggestion to open them :-)
