########################################################################################################################
# Laundry Room                                                                                                         #
########################################################################################################################

- alias: Landing Motion
  id: landing_motion_detected
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.landing_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.landing_motion
      to: "off"
      for: "00:00:30"
    - platform: state
      entity_id: binary_sensor.landing_motion
      to: "off"
      for: "00:02:00"
    - platform: state
      entity_id: binary_sensor.landing_motion
      to: "off"
      for: "00:05:00"
  variables:
    scene_entity_id: "{{ 'scene.LandingEnter' + states('input_select.house_mode') if (trigger.to_state.state == 'on') else 'scene.LandingExit' }}"
  action:
    - service: scene.turn_on
      data:
        entity_id: "{{ scene_entity_id }}"
    # When Joris is still in bed, but Ilse is awake (determined when phone is charging)
    - condition: "{{ not is_state('input_select.house_mode', 'Sleeping') }}"
    - condition: "{{ is_state('sensor.iphone_13_pro_max_battery_state', 'Not Charging')  }}"
    - condition: "{{ is_state('person.joris', 'Home')  }}"
    - service: script.notify_joris
      data:
        message: Joris still sleeping, landing light should be kept off!


