########################################################################################################################
# Maintenance                                                                                                          #
########################################################################################################################
# Nightly network power cycle happens at 4.00AM, we do a power cycle of some other things to ensure they're probably
# reconnected to the network

- alias: Restart Home Assistant at 4.45AM
  id: maintenance_nightly_restart_homeassistant
  trigger:
    - platform: time
      at: "04:45:00"
  action:
    - service: homeassistant.restart

- alias: Reporting light in dressing not turning off
  id: light_dressing_reporting
  trigger:
    - platform: state
      entity_id:
        - light.dressing
        - light.landing
        - light.kitchen
        - light.office
        - light.dining_table
      to: "off"
  variables:
    zombies: "{{ expand(trigger.from_state.attributes.entity_id) | selectattr('state', 'eq', 'on') | list  }}"
    zombies_entity_list: "{{ zombies | map(attribute='entity_id') | join(', ') }}"
  action:
    - condition: template
      value_template: "{{ zombies != [] }}"
    - service: script.notify_joris
      data:
        message: "One or more lamps did not turn off while turning off {{trigger.from_state.attributes.friendly_name}} ({{ zombies_entity_list }})"
