########################################################################################################################
# Presence                                                                                                             #
########################################################################################################################

- alias: Presence Change Notifications
  id: presence_change
  trigger:
    - platform: zone
      entity_id:
        - person.joris
        - person.ilse
      event: enter
      zone: zone.home
    - platform: zone
      entity_id:
        - person.joris
        - person.ilse
      event: leave
      zone: zone.home
  action:
    - service: script.notify_joris
      data:
        title: Home Presence
        message: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state | replace('not_home', 'away')}}"
        expire: "00:05:00"
