########################################################################################################################
# Toilet                                                                                                               #
########################################################################################################################

################################################################################
# Motion                                                                       #
################################################################################

- alias: Toilet Motion
  id: toilet_motion
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.toilet_motion
      to: "off"
      for: "00:04:00"
  variables:
    scene_entity_id: "{{ 'scene.ToiletEnter' + states('input_select.house_mode') if (trigger.to_state.state == 'on') else 'scene.ToiletExit' }}"
  action:
    - service: scene.turn_on
      data:
        entity_id: "{{ scene_entity_id }}"
