---
- name: Creating homeassistant group
  group: name="{{homeassistant_group}}" state=present system=yes
  become: yes

- name: Creating homeassistant user
  user: name="{{homeassistant_user}}" comment="Homeassistant User" group="{{homeassistant_group}}"
        home={{homeassistant_dir}} createhome=no system=yes # Not a login user
  become: yes

- name: Creating homeassistant directories
  file: path="{{item}}" state=directory owner={{homeassistant_user}} group={{homeassistant_group}}
  become: yes
  with_items:
    - "{{homeassistant_dir}}"
    - "{{homeassistant_dir}}/automations"
    - "{{homeassistant_dir}}/scenes"
    - "{{homeassistant_dir}}/inputs"

- name: "Configuring homeassistant automations"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
    - automations/automations.yaml
    - automations/hallway.yaml
    - automations/house_mode.yaml
    - automations/bathroom.yaml
    - automations/bedroom.yaml
    - automations/laundryroom.yaml
    - automations/office.yaml
    - automations/kitchen.yaml
  notify:
    - reload_homeassistant_automations
    # - restart_homeassistant
  tags:
    - hass-config
    - hass-automations
  become: yes

- name: "Configuring homeassistant known_devices (no restart needed)"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
    - known_devices.yaml
  tags:
    - hass-config
  become: yes

- name: "Configuring homeassistant"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
   - configuration.yaml
   - groups.yaml
   - scenes/scenes.yaml
   - scenes/office.yaml
   - scenes/hallway.yaml
   - scenes/bathroom.yaml
   - scenes/livingroom.yaml
   - scenes/laundryroom.yaml
   - scenes/house_mode.yaml
   - scenes/demo.yaml
   - inputs/boolean.yaml
   - inputs/select.yaml
   - scripts.yaml
#   - nest.conf # Nest token needs to be refreshed every so often, installing an invalid one messes up HA
   - phue.conf # No longer neccessary?
  notify:
    - reload_homeassistant_config
    # - restart_homeassistant
  tags:
    - hass-config
  become: yes

- name: "Adding prom2hass.sh script"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}} mode=u+x
  with_items:
   - prom2hass.py
  become: yes

- name: "Ensure all files are owned by the homeassistant user"
  file: path={{homeassistant_dir}} state=directory owner={{homeassistant_user}} group={{homeassistant_group}} recurse=yes
  become: yes

- name: Starting homeassistant docker container
  docker_container:
    name: "{{homeassistant_container_name}}"
    image: "{{homeassistant_container_image}}"
    state: started # Modify and restart iff config has changed
    volumes:
      - "{{homeassistant_dir}}/:/config"
      - /etc/localtime:/etc/localtime:ro
    labels:
      group: homeassistant
    network_mode: host
    recreate: "{{recreate_containers}}"
    env: # https://community.home-assistant.io/t/endless-insecurerequestwarning-errors-with-unifi
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    restart_policy: unless-stopped
    devices:
      - "{{zwave_gateway_device_host}}:{{zwave_gateway_device_container}}"
  become: yes
  tags:
    - homeassistant-container

- name: "Docker post-startup changes"
  shell: "docker exec homeassistant {{item}}"
  with_items:
    - apt-get update
    - apt-get install -y jq
    - wget https://github.com/McKael/samtv/releases/download/v1.0.0/samtvcli-1.0.0-linux-amd64.tar.bz2 -O /tmp/samtvcli.tar.bz2
    - tar xvf /tmp/samtvcli.tar.bz2 -C /tmp
    - cp /tmp/1.0.0/linux-amd64/samtvcli /usr/bin/samtvcli
  become: yes

- name: Install casa-container for homeassistant (aliases only for now)
  include_role:
    name: casa-container
  vars:
    alias_shorthand: "ha"
    container_name: "{{homeassistant_container_name}}"

- name: Modifying sudoers file so homeassistant user can run restart homeassistant container
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{homeassistant_user}} ALL=({{item.user}}) NOPASSWD: {{item.command}}'
    validate: visudo -cf %s
  become: yes
  with_items:
    - {"user": "root", "command": "/usr/bin/timeout * docker restart homeassistant"}

# Restart to deal with Tradfri issues: https://github.com/home-assistant/home-assistant/issues/14386
- name: "Cronjob: restart homeassistant at 4.20AM every night"
  cron: name="Nightly home-assistant restart" minute="20" hour="4" job="/usr/bin/sudo /usr/bin/timeout 180 docker restart homeassistant"
        user={{homeassistant_user}}
  become: yes

- name: "Add iptable rule for Homeassistant"
  iptables: chain=INPUT protocol=tcp destination_port={{homeassistant_port}} source={{casa_subnet}} ctstate=NEW,ESTABLISHED jump=ACCEPT
            comment=Homeassistant
  become: yes
  notify: save_iptables
  tags: [iptables, iptable]
