wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Required to connect to hidden SSIDs
  fast_connect: true
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${dnsname}_fallback-AP
    password: !secret wifi_fallback_ap_password

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption: 
    key: !secret api_encryption_key

# Enable Over-The-Air updates
ota:
  password: !secret ota_password

logger:
#  level: DEBUG # Required for the tracker to show the device