substitutions:
  dnsname: diaper-station
  deviceid: diaper_station
  devicename: Diaper Station

esphome:
  name: ${dnsname}
  platform: ESP32
  board: wemos_d1_mini32

<<: !include .base.yaml

################################################################################
# Airthings Wave Plus BLE sensor                                               #
################################################################################    
# airthings_ble: # Required for the tracker to show the device

# Enable Bluetooth Low Energy
esp32_ble_tracker:

ble_client:
  - mac_address: !secret office_airthings_wave_plus_ble_mac
    id: airthings_office
  - mac_address: !secret bedroom_airthings_wave_plus_ble_mac
    id: airthings_bedroom

sensor:
  - platform: airthings_wave_plus
    ble_client_id: airthings_office
    update_interval: 5min
    temperature:
      name: "Office WavePlus Temperature"
    radon:
      name: "Office WavePlus Radon"
    radon_long_term:
      name: "Office WavePlus Radon Long Term"
    pressure:
      name: "Office WavePlus Pressure"
    humidity:
      name: "Office WavePlus Humidity"
    co2:
      name: "Office WavePlus CO2"
    tvoc:
      name: "Office WavePlus VOC"

  - platform: airthings_wave_plus
    ble_client_id: airthings_bedroom
    update_interval: 5min
    temperature:
      name: "Bedroom WavePlus Temperature"
    radon:
      name: "Bedroom WavePlus Radon"
    radon_long_term:
      name: "Bedroom WavePlus Radon Long Term"
    pressure:
      name: "Bedroom WavePlus Pressure"
    humidity:
      name: "Bedroom WavePlus Humidity"
    co2:
      name: "Bedroom WavePlus CO2"
    tvoc:
      name: "Bedroom WavePlus VOC"
    
################################################################################
# Diaper Weight sensor                                                         #
################################################################################

  - platform: hx711
    id: ${deviceid}_weight
    name: ${devicename} Weight
    dout_pin: 21
    clk_pin: 22
    update_interval: 2s
    filters:
      - calibrate_linear:
          - -76000 -> 0
          - -74000 -> 1
    unit_of_measurement: kg
