substitutions:
  dnsname: sauna
  deviceid: sauna
  devicename: Sauna

esphome:
  name: ${dnsname}
  platform: ESP32
  board: esp32dev
  # Some custom options required for AZ Delivery board
  # https://github.com/esphome/feature-requests/issues/609
  platformio_options: 
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${dnsname}_fallback-AP
    password: !secret wifi_fallback_ap_password


# Enable Home Assistant API
api:
  password: !secret api_password
  encryption: 
    key: !secret api_encryption_key

# Enable Over-The-Air updates
ota:
  password: !secret ota_password

logger:

i2c:
  sda: 21
  scl: 22

switch:
  - platform: gpio
    id: ${deviceid}_front_heater
    name: ${devicename} Front Heater
    pin:
      number: 25
      inverted: True

  - platform: gpio
    id: ${deviceid}_leg_heater
    name: ${devicename} Leg Heater
    pin:
      number: 26
      inverted: True

  - platform: gpio
    id: ${deviceid}_back_heater
    name: ${devicename} Back Heater
    pin:
      number: 33
      inverted: True

# https://esphome.io/components/sensor/bme280.html
sensor:
  - platform: bme280
    temperature:
      id: ${deviceid}_temperature
      name: "${devicename} Temperature"
      oversampling: 16x
    pressure:
      id: ${deviceid}_pressure
      name: "${devicename} Pressure"
    humidity:
      id: ${deviceid}_humidity
      name: "${devicename} Humidity"
    update_interval: 3s
    address: 0x76